os: linux

language: php

services:
  - mongodb

php:
  - 7.2

before_install:
  - yes '' | pecl install -f mongodb

install:
  - travis_retry composer install

before_script:
  - sleep 30

script:
  - vendor/bin/phpunit

after_script:
  - docker-compose down
