os: linux

language: php

services:
  - docker

php:
  - 7.2

before_install:
  - yes '' | pecl install -f mongodb

install:
  - travis_retry composer install

before_script:
  - mkdir -p mongodata
  - docker-compose up -d
  - curl localhost:27017
  - nc -z -w30 127.0.0.1 27017

script:
  - vendor/bin/phpunit

after_script:
  - docker-compose down
